cooking_website/urls.py
from django.urls import path

from . import views

app_name = "cooking_website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("signup", views.SignupView.as_view(), name="signup"),
    path("login", views.MyLoginView.as_view(), name="login"),
    path("logout", views.MyLogoutView.as_view(), name="logout"),
    path("search", views.SearchView.as_view(), name="search"),
    path("recipe/<int:pk>", views.RecipeView.as_view(), name="recipe"),
    path(
        "recipe/<int:pk>/update", views.RecipeUpdateView.as_view(), name="recipe_update"
    ),
    path("recipe/create", views.RecipeCreateView.as_view(), name="recipe_create"),
    path("user/<int:pk>", views.UserView.as_view(), name="user"),
    path("user/<int:pk>/update", views.UserUpdateView.as_view(), name="user_update"),
    path(
        "user/<int:pk>/following",
        views.UserFollowingView.as_view(),
        name="user_following",
    ),
    path(
        "user/<int:pk>/follower", views.UserFollowerView.as_view(), name="user_follower"
    ),
    path("notification", views.NotificationView.as_view(), name="notification"),
    path("like-post", views.like_post, name="like_post"),
    path("follow-post", views.follow_post, name="follow_post"),
]

cooking_website_pj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cooking_website.urls")),
]
if settings.DEBUG:
    from django.contrib.staticfiles.urls import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking_website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from markdown import markdown


class CustomUser(AbstractUser):
    profile = models.TextField(
        verbose_name="プロフィール", null=True, blank=True, max_length=1000
    )
    image = models.ImageField(
        verbose_name="画像", null=True, blank=True, upload_to="images/user/"
    )

    def __str__(self):
        return self.username


class Connection(models.Model):
    followee = models.ForeignKey(
        CustomUser, related_name="is_followee", on_delete=models.CASCADE
    )
    follower = models.ForeignKey(
        CustomUser, related_name="is_follower", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.followee} is followed by {self.follower}"


class Recipe(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=100)
    image = models.ImageField(
        verbose_name="画像", null=True, blank=True, upload_to="images/recipe/"
    )
    description = models.TextField(verbose_name="説明", max_length=5000)
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="更新日時", auto_now=True)
    written_by = models.ForeignKey(
        CustomUser, related_name="recipe", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title

    def get_markdown_description_as_html(self):
        return markdown(self.description)


class Like(models.Model):
    recipe = models.ForeignKey(Recipe, related_name="like", on_delete=models.CASCADE)
    given_by = models.ForeignKey(
        CustomUser, related_name="like", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"A like about {self.recipe} given by {self.given_by}"


class Notification(models.Model):
    content = models.TextField(verbose_name="内容", max_length=200)
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    sender = models.ForeignKey(
        CustomUser, related_name="sent_notification", on_delete=models.CASCADE
    )
    recipient = models.ForeignKey(
        CustomUser, related_name="recept_notification", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"A notification to {self.recipient}"

cooking_website/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import CustomUser, Recipe


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "profile", "image"]


class LoginForm(AuthenticationForm):
    pass


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["username", "profile", "image"]


class RecipeSearchForm(forms.Form):
    pass


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", "image", "description"]

cooking_website/views.py
from django.db.models.base import Model as Model
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    UpdateView,
    ListView,
)
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.db.models import Count, Q
from django.http import JsonResponse

from .models import CustomUser, Recipe, Connection, Like, Notification
from .forms import LoginForm, SignupForm, UserUpdateForm, RecipeSearchForm, RecipeForm


class IndexView(TemplateView):
    template_name = "cooking_website/index.html"


class SignupView(CreateView):
    template_name = "cooking_website/signup.html"
    model = CustomUser
    form_class = SignupForm
    success_url = reverse_lazy("cooking_website:search")

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return response


class MyLoginView(LoginView):
    template_name = "cooking_website/login.html"
    form_class = LoginForm


class MyLogoutView(LoginRequiredMixin, LogoutView):
    pass


class SearchView(LoginRequiredMixin, TemplateView):
    template_name = "cooking_website/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = RecipeSearchForm(self.request.GET)
        if form.is_valid():
            keyword = form.cleaned_data["keyword"]
            if keyword:
                popular_recipes = (
                    Recipe.objects.filter(
                        Q(title__icontains=keyword) | Q(description__icontains=keyword)
                    )
                    .annotate(like_count=Count("like"))
                    .select_related("written_by")
                    .order_by("-like_count")
                    .values(
                        "pk",
                        "title",
                        "image",
                        "description",
                        "written_by__username",
                        "written_by__image",
                    )
                )
                new_recipes = (
                    Recipe.objects.filter(
                        Q(title__icontains=keyword) | Q(description__icontains=keyword)
                    )
                    .select_related("written_by")
                    .order_by("-created_at")
                    .values(
                        "pk",
                        "title",
                        "image",
                        "description",
                        "written_by__username",
                        "written_by__image",
                    )
                )

        else:
            popular_recipes = (
                Recipe.objects.all()
                .annotate(like_count=Count("like"))
                .select_related("written_by")
                .order_by("-like_count")
                .values(
                    "pk",
                    "title",
                    "image",
                    "description",
                    "written_by__username",
                    "written_by__image",
                )
            )
            new_recipes = (
                Recipe.objects.all()
                .select_related("written_by")
                .order_by("-created_at")
                .values(
                    "pk",
                    "title",
                    "image",
                    "description",
                    "written_by__username",
                    "written_by__image",
                )
            )

        context["form"] = form
        context["popular_recipes"] = popular_recipes
        context["new_recipes"] = new_recipes
        return context


class RecipeView(LoginRequiredMixin, DetailView):
    template_name = "cooking_website/recipe.html"
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = context["object"]
        context["like_count"] = recipe.like.all().count()
        context["is_liked"] = Like.objects.filter(
            recipe=recipe, given_by=self.request.user
        ).exists()
        return context


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "cooking_website/recipe_update.html"
    model = Recipe
    form_class = RecipeForm

    def get_success_url(self):
        return reverse_lazy(
            "cooking_website:recipe", kwargs={"pk": self.kwargs.get("pk")}
        )


class RecipeCreateView(LoginRequiredMixin, CreateView):
    template_name = "cooking_website/recipe_create.html"
    model = Recipe
    form_class = RecipeForm

    def get_success_url(self):
        return reverse_lazy("cooking_website:recipe", kwargs={"pk": self.recipe_pk})

    def form_valid(self, form):
        form = form.save(commit=False)
        form.written_by = self.request.user
        form.save()
        self.recipe_pk = form.pk
        return super().form_valid(form)


class UserView(LoginRequiredMixin, DetailView):
    template_name = "cooking_website/user.html"
    model = CustomUser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object = context["object"]
        recipes = object.recipe.all().values("pk", "title", "image")
        context["recipes"] = recipes

        if object.pk != self.request.user.pk:
            context["is_followed"] = Connection.objects.filter(
                followee=object, follower=self.request.user
            ).exists()
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "cooking_website/user_update.html"
    model = CustomUser
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse_lazy(
            "cooking_website:user", kwargs={"pk": self.kwargs.get("pk")}
        )


class UserFollowingView(LoginRequiredMixin, ListView):
    template_name = "cooking_website/user_following.html"
    model = CustomUser
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(CustomUser, pk=self.kwargs.get("pk"))
        query_set = CustomUser.objects.filter(is_followee__follower=user).values(
            "pk", "image", "username"
        )
        return query_set


class UserFollowerView(LoginRequiredMixin, ListView):
    template_name = "cooking_website/user_followed.html"
    model = CustomUser
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(CustomUser, pk=self.kwargs.get("pk"))
        query_set = CustomUser.objects.filter(is_follower__followee=user).values(
            "pk", "image", "username"
        )
        return query_set


class NotificationView(LoginRequiredMixin, ListView):
    template_name = "cooking_website/notification.html"
    model = Notification
    paginate_by = 10

    def get_queryset(self):
        return (
            Notification.objects.filter(recipient=self.request.user)
            .select_related("sender")
            .order_by("-created_at")
            .values("content", "sender__pk")
        )


def like_post(request):
    recipe = get_object_or_404(Recipe, pk=request.POST.get("recipe_pk"))
    like = Like.objects.filter(recipe=recipe, given_by=request.user)

    if like.exists():
        like.delete()
    else:
        Like.objects.create(recipe=recipe, given_by=request.user)

    context = {
        "like_count": recipe.like.all().count(),
    }
    return JsonResponse(context)


def follow_post(request):
    followee = get_object_or_404(CustomUser, pk=request.POST.get("followee_pk"))
    connection = Connection.objects.filter(followee=followee, follower=request.user)

    if connection.exists():
        connection.delete()
        method = "delete"
    else:
        Connection.objects.create(followee=followee, follower=request.user)
        method = "create"

    context = {
        "follower_count": followee.is_followee.all().count(),
        "method": method,
    }
    return JsonResponse(context)

cooking_website/templates/cooking_website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BeEnRecipe</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/base.css' %}">
    {% block extra_style %}{% endblock %}
</head>
<body>
    <header class="header">
        <span class="header-title">
            BeEnRecipe
        </span>
        {% block header %}{% endblock %}
    </header>
    <main class="main">
        {% block main %}{% endblock %}
    </main>
    {% block footer %}
    <footer class="footer">
        <div class="footer-item">
            <a href="{% url 'cooking_website:search' %}" class="footer-item-link">
                <i class="fa-solid fa-magnifying-glass fa-lg"></i>
            </a>
        </div>
        <div class="footer-item">
            <a href="{% url 'cooking_website:user' request.user.pk %}" class="footer-item-link">
                <i class="fa-solid fa-user fa-lg"></i>
            </a>
        </div>
        <div class="footer-item">
            <a href="{% url 'cooking_website:notification' %}" class="footer-item-link">
                <i class="fa-solid fa-bell fa-lg"></i>
            </a>
        </div>
    </footer>
    {% endblock %}
    {% block extra_script %}{% endblock %}
</body>
</html>

cooking_website/templates/cooking_website/index.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/index.css' %}">
{% endblock %}

{% block main %}
<div class="main-body">
    <a href="{% url 'cooking_website:login' %}" class="main-item-link button">
        ログイン
    </a>
    <a href="{% url 'cooking_website:signup' %}" class="main-item-link button">
        会員登録
    </a>
</div>
{% endblock %}

{% block footer %}{% endblock %}

cooking_website/templates/cooking_website/login.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/login.css' %}">
{% endblock %}

{% block main %}
<div class="main-body">
    <form action="" method="post" id="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        <div class="field">
            <button type="submit" class="button">
                ログイン
            </button>
        </div>
    </form>
    <a href="{% url 'cooking_website:signup' %}" class="main-item-link">
            会員登録へ
    </a>
</div>
{% endblock %}

{% block footer %}{% endblock %}

cooking_website/templates/cooking_website/notification.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/user_following.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/notification.css' %}">
{% endblock %}

{% block main %}
<div class="main-body">
    {% if object_list %}
    {% for notification in object_list %}
    <a href="{% url 'cooking_website:user' notification.sender__pk %}" class="main-item-text">
        {{ notification.content }}
    </a>
    {% endfor %}
    {% else %}
    <p class="main-message">
        通知がありません
    </p>
    {% endif %}
    <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="{% url 'cooking_website:notification' %}?page=1" class="pagination-item">&laquo; 先頭へ</a>
        <a href="{% url 'cooking_website:notification' %}?page={{ page_obj.previous_page_number }}" class="pagination-item">前へ</a>
        {% endif %}

        <span class="pagination-item">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_next %}
        <a href="{% url 'cooking_website:notification' %}?page={{ page_obj.next_page_number }}" class="pagination-item">次へ</a>
        <a href="{% url 'cooking_website:notification' %}?page={{ page_obj.paginator.num_pages }}" class="pagination-item">最後へ &raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}

cooking_website/templates/cooking_website/recipe.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/recipe.css' %}">
{% endblock %}

{% block main %}
<div class="main-body">
    <div class="main-body-head">
        <div class="main-image-wrap">
            {% if object.image %}
            <img src="{{ object.image.url }}" alt="" class="main-image">
            {% else %}
            <i class="fa-solid fa-image alternative-image main-image"></i>
            {% endif %}
        </div>
        <div class="main-info-wrap">
            <h1 class="main-title">
                {{ object.title }}
            </h1>
            <div class="main-info">
                <div class="main-like">
                    {% if object.written_by == request.user %}
                    <div class="main-like-wrap">
                        <i class="fa-regular fa-heart fa-2x"></i>
                        <p id="like_count" class="main-like-count">
                            {{ like_count }}
                        </p>
                    </div>
                    <a href="{% url 'cooking_website:recipe_update' object.pk %}" class="button">
                        編集
                    </a>
                    {% else %}
                    <button id="like_button" class="main-like-button">
                        {% if is_liked == True %}
                        <i class="fa-solid fa-heart fa-2x main-like-button-red"></i>
                        {% else %}
                        <i class="fa-regular fa-heart fa-2x"></i>
                        {% endif %}
                        <p id="like_count" class="main-like-count">
                            {{ like_count }}
                        </p>
                    </button>
                    {% endif %}
                </div>
                <a href="{% url 'cooking_website:user' object.written_by.pk %}" class="main-writer-wrap">
                    <div class="main-writer-image-wrap">
                        {% if object.written_by.image %}
                        <img src="{{ object.written_by.image.url }}" alt="" class="main-writer-image">
                        {% else %}
                        <i class="fa-solid fa-circle-user alternative-image main-writer-image"></i>
                        {% endif %}
                    </div>
                    <p class="main-writer-username">
                        {{ object.written_by.username }}
                    </p>
                </a>    
            </div>
            <p class="main-created-at">
                {{ object.created_at }}
            </p>        
        </div>
    </div>
    <div class="main-body-foot">
        <p class="main-description">
            {{ object.get_markdown_description_as_html | safe }}
        </p>
    </div>
</div>
{% endblock %}

cooking_website/templates/cooking_website/search.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/search.css' %}">
{% endblock %}

{% block header %}
<a href="{% url 'cooking_website:recipe_create' %}" class="recipe-create">
    <i class="fa-solid fa-pen-to-square"></i>
    <p class="recipe-create-text">
        レシピを書く
    </p>
</a>
<form action="" method="get" class="search">
    <span class="search-item-icon">
        <i class="fa-solid fa-magnifying-glass"></i>
    </span>
    <div class="search-body">
        {{ form.keyword }}
    </div>
</form>
{% endblock %}

{% block main %}
<div class="main-section">
    <h2 class="main-section-title">人気のレシピ</h2>
    <div class="main-section-body">
        {% for recipe in popular_recipes %}
        <a href="{% url 'cooking_website:recipe' recipe.pk %}" class="main-section-item">
            <div class="main-section-item-head">
                {% if recipe.image %}
                <img src="{% get_media_prefix %}{{ recipe.image }}" alt="" class="main-section-item-image">
                {% else %}
                <i class="fa-solid fa-image fa-10x alternative-image"></i>
                {% endif %}
                <div class="main-section-item-right">
                    <h3 class="main-section-item-title">
                        {{ recipe.title }}
                    </h3>
                    <div class="main-section-item-user">
                        <div class="main-section-item-user-image-wrap">
                            {% if recipe.written_by__image %}
                            <img src="{% get_media_prefix %}{{ recipe.written_by__image }}" alt="" class="main-section-item-user-image">
                            {% else %}
                            <i class="fa-solid fa-circle-user fa-lg alternative-image"></i>
                            {% endif %}    
                        </div>
                        <p class="main-section-item-user-text">
                            {{ recipe.written_by__username }}
                        </p>
                    </div>        
                </div>
            </div>
            <div class="main-section-item-foot">
                <p class="main-section-item-text">                
                    {{ recipe.description }}
                </p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
<div class="main-section">
    <h2 class="main-section-title">新着レシピ</h2>
    <div class="main-section-body">
        {% for recipe in new_recipes %}
        <a href="{% url 'cooking_website:recipe' recipe.pk %}" class="main-section-item">
            <div class="main-section-item-head">
                {% if recipe.image %}
                <img src="{% get_media_prefix %}{{ recipe.image }}" alt="" class="main-section-item-image">
                {% else %}
                <i class="fa-solid fa-image fa-10x alternative-image"></i>
                {% endif %}
                <div class="main-section-item-right">
                    <h3 class="main-section-item-title">
                        {{ recipe.title }}
                    </h3>
                    <div class="main-section-item-user">
                        <div class="main-section-item-user-image-wrap">
                            {% if recipe.written_by__image %}
                            <img src="{% get_media_prefix %}{{ recipe.written_by__image }}" alt="" class="main-section-item-user-image">
                            {% else %}
                            <i class="fa-solid fa-circle-user fa-lg alternative-image"></i>
                            {% endif %}    
                        </div>
                        <p class="main-section-item-user-text">
                            {{ recipe.written_by__username }}
                        </p>
                    </div>        
                </div>
            </div>
            <div class="main-section-item-foot">
                <p class="main-section-item-text">                
                    {{ recipe.description }}
                </p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

cooking_website/templates/cooking_website/sign_up.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/sign_up.css' %}">
{% endblock %}

{% block main %}
<div class="main__body">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        <div class="field">
            <button type="submit" class="button">
                会員登録
            </button>
        </div>
    </form>
    <a href="{% url 'cooking_website:index' %}" class="main__item-link">
        トップ画面へ
    </a>
</div>
{% endblock %}

{% block footer %}{% endblock %}

cooking_website/templates/cooking_website/signup.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/login.css' %}">
{% endblock %}

{% block main %}
<div class="main-body">
    <form action="" method="post" enctype="multipart/form-data" id="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        <div class="field">
            <button type="submit" class="button">
                会員登録
            </button>
        </div>
    </form>
    <a href="{% url 'cooking_website:index' %}" class="main-item-link">
        トップ画面へ
    </a>
</div>
{% endblock %}

{% block footer %}{% endblock %}

cooking_website/templates/cooking_website/user.html
{% extends 'cooking_website/base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="{% static 'cooking_website/css/user.css' %}">
{% endblock %}

{% block header %}
<form action="{% url 'cooking_website:logout' %}" method="post" class="heaer-form">
    {% csrf_token %}
    <button type="submit" class="header-form-button">
        ログアウト            
    </button>
</form>
{% endblock %}

{% block main %}
<div class="main-body">
    <div class="main-body-head">
        <div class="main-item">
            <div class="main-item-head">
                <div>
                    {% if object.image %}
                    <img src="{{ object.image.url }}" alt="" class="main-item-image">
                    {% else %}
                    <i class="fa-solid fa-circle-user fa-6x alternative-image"></i>
                    {% endif %}   
                </div>
                <p class="main-item-username">
                    {{ object.username }}
                </p>
            </div>
            <div class="main-item-foot">
                <p class="main-item-profile">
                    {% if object.profile %}
                    {{ object.profile }}
                    {% else %}
                    プロフィール未設定
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="main-item">
            <div class="main-item-head">
                <a href="{% url 'cooking_website:user_following' object.pk %}" class="main-item-link">
                    {{ object.is_follower.all|length }} フォロー中
                </a>
                <a href="{% url 'cooking_website:user_follower' object.pk %}" id="follower" class="main-item-link">
                    {{ object.is_followee.all|length }} フォロワー
                </a>
            </div>
            <div class="main-item-foot">
                {% if request.user.pk == object.pk %}
                <a href="{% url 'cooking_website:user_update' object.pk %}" class="button">
                    編集
                </a>
                {% else %}
                {% if is_followed == True %}
                <button id="follow_button" class="button following">
                    フォロー中
                </button>
                {% else %}
                <button id="follow_button" class="button">
                    フォロー
                </button>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="main-body-foot">
        <div class="main-heading">
            <i class="fa-solid fa-utensils fa-lg"></i>
            <h2 class="main-item-title">
                レシピ
            </h2>
            <p class="main-item-caption">
                ({{ recipes|length }})
            </p>    
        </div>
        <div class="main-list">
            {% for recipe in recipes %}
            <a href="{% url 'cooking_website:recipe' recipe.pk %}" class="main-list-item">
                {% if recipe.image %}
                <img src="{% get_media_prefix %}{{ recipe.image }}" alt="" class="main-list-item-image">
                {% else %}
                <i class="fa-solid fa-image fa-8x alternative-image"></i>
                {% endif %}
                <p class="main-list-item-title">
                    {{ recipe.title }}
                </p>
            </a>
            {% endfor %}    
        </div>
    </div>
</div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript">
    document.getElementById("follow_button").addEventListener("click", async(e) => {
        e.preventDefault();
        const url = "{% url 'cooking_website:follow_post' %}";
        try {
            const response = await fetch(url, {
                method: "POST",
                body: "followee_pk={{ object.pk }}",
                headers: {
                    "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
                    "X-CSRFToken": "{{ csrf_token }}",
                    },
            });
            const json_data = await response.json();
            document.getElementById("follower").textContent = json_data.follower_count + " フォロワー";
                follow_button = document.getElementById("follow_button");
                follow_button.classList.toggle("following")
                if (json_data.method == "create") {
                    follow_button.textContent = "フォロー中"
                } else {
                    follow_button.textContent = "フォロー" 
                }
        }
        catch (error) {
            console.log(error);
        }
    });
</script>
{% endblock %}